name: action_inc_taxi_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  crypto: ^3.0.2

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.0
  cached_network_image: ^3.3.0
  flutter_screenutil: ^5.9.0
  flutter_hooks: ^0.20.1
  flutter_svg: ^2.0.9

  
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  
  auto_route: ^7.8.0

  
  dio: ^5.4.0
  connectivity_plus: ^5.0.0

  
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  
  geolocator: ^11.0.0
  geocoding: ^3.0.0

  
  get_it: ^7.6.7

  
  intl: ^0.19.0
  logger: ^2.0.0
  formz: ^0.7.0
  firebase_core: ^2.32.0
  uuid: ^4.5.2
  file_picker: ^8.0.7



dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0
  very_good_analysis: ^5.1.0

  
  mocktail: ^1.0.0
  bloc_test: ^9.0.0

  
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  auto_route_generator: ^7.3.2

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/logo/

  fonts:
    - family: Lufga
      fonts:
        - asset: assets/fonts/LufgaRegular.ttf
          weight: 400
        - asset: assets/fonts/LufgaSemiBold.ttf
          weight: 600

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
